# Docker compose for Zabbix server, with dashboar, database and agent to monitoring itself.
services:
  # DB
  postgres-server:
    image: postgres:15-alpine
    container_name: zabbix-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./zbx_env/var/lib/postgresql/data:/var/lib/postgresql/data:rw
  # Server
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:7.0-ubuntu-latest
    container_name: zabbix-server
    restart: always
    ports:
    - "10051:10051"
    environment:
    - DB_SERVER_HOST=${DB_SERVER_HOST}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
    - postgres-server
  # Dashboard
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:7.0-ubuntu-latest
    container_name: zabbix-web
    restart: always
    expose:
    - "8080"
    environment:
    - DB_SERVER_HOST=${DB_SERVER_HOST}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    - ZBX_SERVER_HOST=${ZBX_SERVER_HOST}
    - PHP_TZ=${PHP_TZ}
    depends_on:
    - zabbix-server

  nginx-proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy
    restart: always
    ports:
      # web proxy HTTP & HTTPS
      - "80:80"
      - "443:443"
      # proxy admin panel
      - "81:81"
    volumes:
      - ./npm_data:/data
      - ./npm_letsencrypt:/etc/letsencrypt
    depends_on:
      - zabbix-web

networks:
 default:
  name: zabbix-net
  driver: bridge